dapp: packages/dapp
api: packages/api
ganache-bootstrap: packages/ganache-bootstrap
contracts: packages/contracts
exchange-connector: packages/exchange-connector
deployer: packages/deployer
stats: packages/stats
