/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from "ethereum-types";

import * as AbiEncoder from "../generated-artifacts/AbiEncoder.json";
import * as ASelfCustody from "../generated-artifacts/ASelfCustody.json";
import * as ATotlePrimary from "../generated-artifacts/ATotlePrimary.json";
import * as Authority from "../generated-artifacts/Authority.json";
import * as AWeth from "../generated-artifacts/AWeth.json";
import * as Distribution from "../generated-artifacts/Distribution.json";
import * as Drago from "../generated-artifacts/Drago.json";
import * as DragoEventful from "../generated-artifacts/DragoEventful.json";
import * as DragoFactory from "../generated-artifacts/DragoFactory.json";
import * as DragoRegistry from "../generated-artifacts/DragoRegistry.json";
import * as ERC20 from "../generated-artifacts/ERC20.json";
import * as Erc20Proxy from "../generated-artifacts/Erc20Proxy.json";
import * as Exchange from "../generated-artifacts/Exchange.json";
import * as ExchangesAuthority from "../generated-artifacts/ExchangesAuthority.json";
import * as Faucet from "../generated-artifacts/Faucet.json";
import * as HGetDragoData from "../generated-artifacts/HGetDragoData.json";
import * as Inflation from "../generated-artifacts/Inflation.json";
import * as Migrations from "../generated-artifacts/Migrations.json";
import * as NavVerifier from "../generated-artifacts/NavVerifier.json";
import * as Owned from "../generated-artifacts/Owned.json";
import * as OwnedUninitialized from "../generated-artifacts/OwnedUninitialized.json";
import * as ProofOfPerformance from "../generated-artifacts/ProofOfPerformance.json";
import * as RigoToken from "../generated-artifacts/RigoToken.json";
import * as SigVerifier from "../generated-artifacts/SigVerifier.json";
import * as TokenTransferProxy from "../generated-artifacts/TokenTransferProxy.json";
import * as TotlePrimary from "../generated-artifacts/TotlePrimary.json";
import * as UnlimitedAllowanceToken from "../generated-artifacts/UnlimitedAllowanceToken.json";
import * as Vault from "../generated-artifacts/Vault.json";
import * as VaultEventful from "../generated-artifacts/VaultEventful.json";
import * as VaultFactory from "../generated-artifacts/VaultFactory.json";
import * as WETH9 from "../generated-artifacts/WETH9.json";
import * as ZeroExExchangeHandler from "../generated-artifacts/ZeroExExchangeHandler.json";
export const artifacts = {
  Migrations: Migrations as ContractArtifact,
  Distribution: Distribution as ContractArtifact,
  Faucet: Faucet as ContractArtifact,
  HGetDragoData: HGetDragoData as ContractArtifact,
  Drago: Drago as ContractArtifact,
  DragoEventful: DragoEventful as ContractArtifact,
  DragoRegistry: DragoRegistry as ContractArtifact,
  Vault: Vault as ContractArtifact,
  VaultEventful: VaultEventful as ContractArtifact,
  Authority: Authority as ContractArtifact,
  ExchangesAuthority: ExchangesAuthority as ContractArtifact,
  DragoFactory: DragoFactory as ContractArtifact,
  NavVerifier: NavVerifier as ContractArtifact,
  SigVerifier: SigVerifier as ContractArtifact,
  ASelfCustody: ASelfCustody as ContractArtifact,
  ATotlePrimary: ATotlePrimary as ContractArtifact,
  AWeth: AWeth as ContractArtifact,
  VaultFactory: VaultFactory as ContractArtifact,
  Inflation: Inflation as ContractArtifact,
  ProofOfPerformance: ProofOfPerformance as ContractArtifact,
  RigoToken: RigoToken as ContractArtifact,
  ERC20: ERC20 as ContractArtifact,
  UnlimitedAllowanceToken: UnlimitedAllowanceToken as ContractArtifact,
  WETH9: WETH9 as ContractArtifact,
  AbiEncoder: AbiEncoder as ContractArtifact,
  Owned: Owned as ContractArtifact,
  OwnedUninitialized: OwnedUninitialized as ContractArtifact,
  Erc20Proxy: Erc20Proxy as ContractArtifact,
  Exchange: Exchange as ContractArtifact,
  TokenTransferProxy: TokenTransferProxy as ContractArtifact,
  TotlePrimary: TotlePrimary as ContractArtifact,
  ZeroExExchangeHandler: ZeroExExchangeHandler as ContractArtifact
};
