version: 2.0

references:
  workspace_root: &workspace_root
    ~/rigoblock-monorepo

  timezone: &timezone
    "/usr/share/zoneinfo/Europe/Rome"

  node_image: &node_image
    circleci/node:8.10.0-stretch

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  setup:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: *node_image
    steps:
      - checkout
      - restore_cache:
          key: rigoblock-monorepo-{{ checksum "yarn.lock" }}
      - run:
          name: Install lerna and monorepo dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Installing all dependencies
          command: yarn bootstrap
      - save_cache:
          key: rigoblock-monorepo-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/dapp/node_modules
            - packages/ganache-bootstrap/node_modules
            - packages/api/node_modules
            - packages/contracts/node_modules
            - packages/deployer/node_modules
            - packages/exchange-connector/node_modules
            - .cache/yarn
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - node_modules
            - packages/dapp/node_modules
            - packages/ganache-bootstrap/node_modules
            - packages/api/node_modules
            - packages/contracts/node_modules
            - packages/deployer/node_modules
            - packages/exchange-connector/node_modules
            - .cache/yarn
  test-unit-dapp:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: circleci/node:8.10-stretch
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: JS unit tests
          command: npx lerna run --scope @rigoblock/dapp test:cov --stream
      - store_artifacts:
          path: coverage/dapp/lcov-report

  build-contracts:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
      NODE_ENV: production
    docker:
      - image: *node_image
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Building deployer
          command: yarn build:deployer
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Starting ganache cli
          command: npx lerna run --scope @rigoblock/dapp ganache --stream
          background: true
      - run:
          name: Wait for ganache cli
          command: dockerize -wait tcp://localhost:8545 -timeout 1m
      - run:
          name: Building contracts
          command: yarn build:contracts
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - packages/contracts/artifacts
            - packages/contracts/dist
            - packages/deployer/dist

  test-contracts:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
      NODE_ENV: production
    docker:
      - image: *node_image
    steps:
      - checkout
      - *attach_workspace
      - run:
         name: Test contracts
         command: npx lerna run --scope @rigoblock/contracts test --stream

  build-api:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
      NODE_ENV: production
    docker:
      - image: *node_image
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Building dist
          command: yarn build:api
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - packages/api/dist

  push-api-changes:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: *node_image
    steps:
      - checkout
      - run:
          name: Cloning git subrepo
          command: git clone https://github.com/ingydotnet/git-subrepo ../git-subrepo
      - run:
          name: Pushing changes to API subrepo
          command: source ../git-subrepo/.rc && yarn push-api-subrepo

  build-exchange-connector:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: *node_image
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Building dist
          command: yarn build:exchange-connector
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - packages/exchange-connector/dist

  test-exchange-connector:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: *node_image
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Running unit tests
          command: npx lerna run --scope @rigoblock/exchange-connector test:unit --stream
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - packages/exchange-connector/dist

  build-dapp:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
      CI: false
      REACT_APP_TEST: true
      NODE_ENV: production
    docker:
      - image: *node_image
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Building dist
          command: yarn build:dapp
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - packages/dapp/dist

  test-feature-dapp:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: circleci/node:8.10-stretch-browsers
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Starting HTTP server
          command: npx lerna run --scope @rigoblock/dapp start --stream
          background: true
      - run:
          name: Wait for HTTP server
          command: dockerize -wait tcp://localhost:8080 -timeout 1m
      - run:
          name: JS feature tests
          command: npx lerna run --scope @rigoblock/dapp test:feature:debug --stream
      - store_artifacts:
          path: packages/dapp/output


  deploy-dapp-staging:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    machine: true
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Install Flynn CLI
          command: 'L=~/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L'
      - run:
          name: Add Flynn cluster
          command: "~/flynn cluster add -p hSeBWhP7I5Q/C0nAXQ5L30fW1B956NurbxbQ/TQSXPI= staging dev-02.endpoint.network c6e549fcc2f7f2145db34a96c7baaab5"
      - run:
          name: Flynn ping
          command: "~/flynn apps"
      - run:
          name: Download flynn cert
          command: "curl https://s3-eu-west-1.amazonaws.com/rigoblock/ca-cert.cer -o ca.crt"
      - run:
          name: Cert folder
          command: "sudo mkdir -p /etc/docker/certs.d/docker.dev-02.endpoint.network/"
      - run:
          name: Move cert
          command: "sudo mv ca.crt /etc/docker/certs.d/docker.dev-02.endpoint.network/"
      - run:
          name: Restart docker
          command: "sudo service docker restart"
      - run:
          name: Flynn set docker
          command: "~/flynn docker set-push-url && ~/flynn docker login"
      - run:
          name: Building docker image
          command: "docker build -t staging --build-arg NPM_KEY=$NPM_KEY --build-arg NGINX_USERNAME=$NGINX_USERNAME --build-arg NGINX_PASSWORD=$NGINX_PASSWORD -f ./packages/dapp/Dockerfile ."
      - run:
          name: Flynn push
          command: "~/flynn -a dapp-staging docker push staging:latest"
      - run:
          name: Flynn scale
          command: "~/flynn -a dapp-staging scale app=1"
      - run:
          name: Tag image with version
          command: |
            NUMBER=$(git log --pretty=oneline | wc -l)
            DATE=$(date +%Y.%m.%d)
            TAG=$(git tag --contains `git rev-list --tags --max-count=1` | grep dapp | cut -d '@' -f3)
            HASH=$(git rev-parse --short HEAD)
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION=$TAG-$BRANCH-$DATE-commit-$HASH-$NUMBER
            echo "export VERSION=$VERSION" >> $BASH_ENV
            source $BASH_ENV
            docker tag staging rb-registry.endpoint.network/webapp-v2:latest
            docker tag staging rb-registry.endpoint.network/webapp-v2:$VERSION
      - run:
          name: Login with private Docker registry
          command: |
            docker login https://rb-registry.endpoint.network/ -u wnz99 -p $JENKINS_PASSWORD
      - run:
          name: Push image to private registry
          command: |
            docker push rb-registry.endpoint.network/webapp-v2:$VERSION
      - run:
          name: Update Rancher deployment
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
            wget https://github.com/rancher/cli/releases/download/v2.0.3-rc1/rancher-linux-amd64-v2.0.3-rc1.tar.gz -O rancher-linux-amd64-v2.0.3-rc1.tar.gz
            tar xzvf rancher-linux-amd64-v2.0.3-rc1.tar.gz
            cd rancher-v2.0.3-rc1/
            chmod +x rancher
            sudo mv ./rancher /usr/local/bin/rancher
            echo "1" | rancher login https://rb-rancher.endpoint.network/v3 --token $RANCHER_TOKEN
            rancher kubectl set image deployment/webapp-v2-staging webapp-v2-staging=rb-registry.endpoint.network/webapp-v2:$VERSION

  deploy-storybook-staging:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    machine: true
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Install Flynn CLI
          command: 'L=~/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L'
      - run:
          name: Add Flynn cluster
          command: "~/flynn cluster add -p hSeBWhP7I5Q/C0nAXQ5L30fW1B956NurbxbQ/TQSXPI= staging dev-02.endpoint.network c6e549fcc2f7f2145db34a96c7baaab5"
      - run:
          name: Flynn ping
          command: "~/flynn apps"
      - run:
          name: Download flynn cert
          command: "curl https://s3-eu-west-1.amazonaws.com/rigoblock/ca-cert.cer -o ca.crt"
      - run:
          name: Cert folder
          command: "sudo mkdir -p /etc/docker/certs.d/docker.dev-02.endpoint.network/"
      - run:
          name: Move cert
          command: "sudo mv ca.crt /etc/docker/certs.d/docker.dev-02.endpoint.network/"
      - run:
          name: Restart docker
          command: "sudo service docker restart"
      - run:
          name: Flynn set docker
          command: "~/flynn docker set-push-url && ~/flynn docker login"
      - run:
          name: Building docker image
          command: "docker build -t storybook-staging --build-arg NPM_KEY=$NPM_KEY --build-arg NGINX_USERNAME=$NGINX_USERNAME --build-arg NGINX_PASSWORD=$NGINX_PASSWORD -f ./packages/dapp/Dockerfile.storybook ."
      - run:
          name: Flynn push
          command: "~/flynn -a storybook-staging docker push storybook-staging:latest"
      - run:
          name: Flynn scale
          command: "~/flynn -a storybook-staging scale app=1"
      - run:
          name: Tag image with version
          command: |
            NUMBER=$(git log --pretty=oneline | wc -l)
            DATE=$(date +%Y.%m.%d)
            TAG=$(git tag --contains `git rev-list --tags --max-count=1` | grep dapp | cut -d '@' -f3)
            HASH=$(git rev-parse --short HEAD)
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION=$TAG-$BRANCH-$DATE-commit-$HASH-$NUMBER
            echo "export VERSION=$VERSION" >> $BASH_ENV
            source $BASH_ENV
            docker tag storybook-staging rb-registry.endpoint.network/webapp-v2-storybook:latest
            docker tag storybook-staging rb-registry.endpoint.network/webapp-v2-storybook:$VERSION
      - run:
          name: Login with private Docker registry
          command: |
            docker login https://rb-registry.endpoint.network/ -u wnz99 -p $JENKINS_PASSWORD
      - run:
          name: Push image to private registry
          command: |
            docker push rb-registry.endpoint.network/webapp-v2-storybook:$VERSION
      - run:
          name: Update Rancher deployment
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
            wget https://github.com/rancher/cli/releases/download/v2.0.3-rc1/rancher-linux-amd64-v2.0.3-rc1.tar.gz -O rancher-linux-amd64-v2.0.3-rc1.tar.gz
            tar xzvf rancher-linux-amd64-v2.0.3-rc1.tar.gz
            cd rancher-v2.0.3-rc1/
            chmod +x rancher
            sudo mv ./rancher /usr/local/bin/rancher
            echo "1" | rancher login https://rb-rancher.endpoint.network/v3 --token $RANCHER_TOKEN
            rancher kubectl set image deployment/webapp-v2-staging-storybook webapp-v2-staging-storybook=rb-registry.endpoint.network/webapp-v2-storybook:$VERSION

workflows:
  version: 2
  rigoblock:
    jobs:
      - setup
      - build-exchange-connector:
          requires:
            - setup
      - test-exchange-connector:
          requires:
            - build-exchange-connector
      - test-unit-dapp:
          requires:
            - setup
      - build-contracts:
          requires:
            - test-unit-dapp
      - test-contracts:
          requires:
            - build-contracts
      - build-api:
          requires:
            - build-contracts
      - build-dapp:
          requires:
            - build-api
      # - push-api-changes:
      #     requires:
      #       - build-api
      #     filters:
      #       branches:
      #         only: master
      - test-feature-dapp:
          requires:
            - build-dapp
      - deploy-dapp-staging:
          requires:
            - test-unit-dapp
            - build-dapp
            - test-feature-dapp
          filters:
            branches:
              only: master
      - deploy-storybook-staging:
          requires:
            - test-unit-dapp
            - build-dapp
            - test-feature-dapp
          filters:
            branches:
              only: master
