version: 2.0

references:
  workspace_root: &workspace_root
    ~/rigoblock-monorepo

  timezone: &timezone
    "/usr/share/zoneinfo/Europe/Rome"

  node_image: &node_image
    circleci/node:8.10.0-stretch

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  setup:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: *node_image
    steps:
      - checkout
      - restore_cache:
          key: monorepo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install lerna and monorepo dependencies
          command: yarn
      - run:
          name: Installing all dependencies
          command: npx lerna boostrap
      - save_cache:
          key: monorepo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - *workspace_root

  build-dapp:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: *node_image
    steps:
      - restore_cache:
          key: monorepo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Building dist
          command: npx lerna run --scope rigoblock-dapp build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - packages/rigoblock-dapp/dist

  test-unit-dapp:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: circleci/node:8.10-stretch
    steps:
      - *attach_workspace
      - restore_cache:
          key: monorepo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: JS unit tests
          command: npx lerna run --scope rigoblock-dapp test:unit

  test-feature:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    docker:
      - image: circleci/node:8.10-stretch-browsers
    steps:
      - *attach_workspace
      - restore_cache:
          key: monorepo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Starting server
          command: yarn start
          background: true
      - run:
          name: JS feature tests
          command: yarn test:feature

  deploy-staging:
    working_directory: *workspace_root
    environment:
      TZ: *timezone
    machine: true
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          key: monorepo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Flynn CLI
          command: 'L=~/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L'
      - run:
          name: Add Flynn cluster
          command: "~/flynn cluster add -p hSeBWhP7I5Q/C0nAXQ5L30fW1B956NurbxbQ/TQSXPI= staging dev-02.endpoint.network c6e549fcc2f7f2145db34a96c7baaab5"
      - run:
          name: Flynn ping
          command: "~/flynn apps"
      - run:
          name: Download flynn cert
          command: "curl https://s3-eu-west-1.amazonaws.com/rigoblock/ca-cert.cer -o ca.crt"
      - run:
          name: Cert folder
          command: "sudo mkdir -p /etc/docker/certs.d/docker.dev-02.endpoint.network/"
      - run:
          name: Move cert
          command: "sudo mv ca.crt /etc/docker/certs.d/docker.dev-02.endpoint.network/"
      - run:
          name: Restart docker
          command: "sudo service docker restart"
      - run:
          name: Flynn set docker
          command: "~/flynn docker set-push-url && ~/flynn docker login"
      - run:
          name: Building docker image
          command: "cd ./packages/rigoblock-dapp && docker build -t staging . "
      - run:
          name: Flynn push
          command: "~/flynn -a dapp-staging docker push staging:latest"
      - run:
          name: Flynn push
          command: "~/flynn -a dapp-staging scale app=1"

workflows:
  version: 2
  rigoblock:
    jobs:
      - setup
      - test-unit-dapp:
          requires:
            - setup
      - build-dapp:
          requires:
            - test-unit-dapp

      # - test-feature:
      #     requires:
      #       - test-unit
      # - deploy-staging:
      #     requires:
      #       - test-feature
      #       - test-unit
      #       - build
          # filters:
          #   branches:
          #     only: master
