/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from "ethereum-types";

import * as AbiEncoder from "../generated-artifacts/AbiEncoder.json";
import * as ASelfCustody from "../generated-artifacts/ASelfCustody.json";
import * as AUniswapV2 from "../generated-artifacts/AUniswapV2.json";
import * as AUniswapV3 from "../generated-artifacts/AUniswapV3.json";
import * as AUniswapV3NPM from "../generated-artifacts/AUniswapV3NPM.json";
import * as Authority from "../generated-artifacts/Authority.json";
import * as AWeth from "../generated-artifacts/AWeth.json";
import * as Distribution from "../generated-artifacts/Distribution.json";
import * as Drago from "../generated-artifacts/Drago.json";
import * as DragoEventful from "../generated-artifacts/DragoEventful.json";
import * as DragoFactory from "../generated-artifacts/DragoFactory.json";
import * as DragoRegistry from "../generated-artifacts/DragoRegistry.json";
import * as ExchangesAuthority from "../generated-artifacts/ExchangesAuthority.json";
import * as Faucet from "../generated-artifacts/Faucet.json";
import * as GrgVault from "../generated-artifacts/GrgVault.json";
import * as HGetDragoData from "../generated-artifacts/HGetDragoData.json";
import * as Inflation from "../generated-artifacts/Inflation.json";
import * as Migrations from "../generated-artifacts/Migrations.json";
import * as NavVerifier from "../generated-artifacts/NavVerifier.json";
import * as ProofOfPerformance from "../generated-artifacts/ProofOfPerformance.json";
import * as RigoToken from "../generated-artifacts/RigoToken.json";
import * as SigVerifier from "../generated-artifacts/SigVerifier.json";
import * as Staking from "../generated-artifacts/Staking.json";
import * as StakingProxy from "../generated-artifacts/StakingProxy.json";
import * as UnlimitedAllowanceToken from "../generated-artifacts/UnlimitedAllowanceToken.json";
import * as Vault from "../generated-artifacts/Vault.json";
import * as VaultEventful from "../generated-artifacts/VaultEventful.json";
import * as VaultFactory from "../generated-artifacts/VaultFactory.json";
export const artifacts = {
  Migrations: Migrations as ContractArtifact,
  Distribution: Distribution as ContractArtifact,
  Faucet: Faucet as ContractArtifact,
  HGetDragoData: HGetDragoData as ContractArtifact,
  Drago: Drago as ContractArtifact,
  DragoEventful: DragoEventful as ContractArtifact,
  DragoRegistry: DragoRegistry as ContractArtifact,
  Vault: Vault as ContractArtifact,
  VaultEventful: VaultEventful as ContractArtifact,
  Authority: Authority as ContractArtifact,
  ExchangesAuthority: ExchangesAuthority as ContractArtifact,
  DragoFactory: DragoFactory as ContractArtifact,
  NavVerifier: NavVerifier as ContractArtifact,
  SigVerifier: SigVerifier as ContractArtifact,
  ASelfCustody: ASelfCustody as ContractArtifact,
  AUniswapV2: AUniswapV2 as ContractArtifact,
  AUniswapV3: AUniswapV3 as ContractArtifact,
  AUniswapV3NPM: AUniswapV3NPM as ContractArtifact,
  AWeth: AWeth as ContractArtifact,
  VaultFactory: VaultFactory as ContractArtifact,
  Inflation: Inflation as ContractArtifact,
  ProofOfPerformance: ProofOfPerformance as ContractArtifact,
  RigoToken: RigoToken as ContractArtifact,
  GrgVault: GrgVault as ContractArtifact,
  Staking: Staking as ContractArtifact,
  StakingProxy: StakingProxy as ContractArtifact,
  UnlimitedAllowanceToken: UnlimitedAllowanceToken as ContractArtifact,
  AbiEncoder: AbiEncoder as ContractArtifact
};
