version: '3.2'
services:
  arena:
    image: vshjxyz/arena:latest
    container_name: arena
    ports:
      - "4567"
    networks:
      - stats
    links:
      - redis
    volumes:
      - ./config/arena/arena.prod.conf.json:/opt/arena/src/server/config/index.json:ro
    labels:
      traefik.backend: "arena"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${ARENA_URI}"
      traefik.docker.network: "stats_stats"
      traefik.port: "4567"
      traefik.frontend.auth.basic.users: "${ARENA_CREDENTIALS}"

  bull:
    container_name: bull
    environment:
      REDIS_HOST: redis
      TELEGRAF_HOST: telegraf
    build:
      context: ../../
      dockerfile: ./packages/data-collector/Dockerfile
      args:
        - NPM_KEY=${NPM_KEY}
    networks:
      - stats

networks:
    stats:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.20.1.0/16
