version: '3.2'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  arena:
    image: vshjxyz/arena:latest
    container_name: arena-data-collector
    ports:
      - "4568:4568"
    volumes:
      - ./config/arena/arena.conf.json:/opt/arena/src/server/config/index.json:ro
    environment:
      ARENA_PORT: 4568
    links:
      - redis

  couchdb:
    image: couchdb:latest
    container_name: couchdb
    ports:
    - "5984:5984"
    - "5986:5986"
    env_file:
      - 'env.couchdb'
    volumes:
       - ./config/couchdb/local.ini:/opt/couchdb/etc/local.ini
       - ./couchdb-data:/opt/couchdb/data
