debug = false

logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[entryPoints]
 [entryPoints.traefik]
   address=":8080"
  #  [entryPoints.traefik.auth]
    #  [entryPoints.traefik.auth.basic]
    #    users = [
    #      "admin:$apr1$CmyX3sA9$iDyMOjnxCzCrz12iKYPCv0"
    #    ]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[api]
entrypoint="traefik"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "endpoint.network"
watch = true
exposedByDefault = false

[acme]
email = "david@rigoblock.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"