import { MemoryRouter } from 'react-router-dom'
import { Provider } from 'react-redux'
import { mount } from 'enzyme'
import BaseTemplate from './BaseTemplate.jsx'
import React from 'react'
import mockStore from '../../../fixtures/store'
import toJson from 'enzyme-to-json'

const store = mockStore({ mockFn: jest.fn })

// initialEntries on MemoryRouter prevents shapshot breaking
// each time random keys are generated by the router
const wrapper = mount(
  <Provider store={store}>
    <MemoryRouter initialEntries={[{ key: 'testKey' }]}>
      <BaseTemplate>Test Content</BaseTemplate>
    </MemoryRouter>
  </Provider>
)

describe('BaseTemplate component', () => {
  it('renders correctly', () => {
    expect(toJson(wrapper)).toMatchSnapshot()
  })
})
