import { MemoryRouter } from 'react-router-dom'
import { Provider } from 'react-redux'
import { mount } from 'enzyme'
import React from 'react'
import VaultTransactionsTable from './VaultTransactionsTable.jsx'
import mockStore from '../../../fixtures/store'
import toJson from 'enzyme-to-json'

const store = mockStore({ mockFn: jest.fn })

// initialEntries on MemoryRouter prevents shapshot breaking
// each time random keys are generated by the router
const wrapper = mount(
  <Provider store={store}>
    <MemoryRouter initialEntries={[{ key: 'testKey' }]}>
      <VaultTransactionsTable vaultAddress="0x86a1ba4d485ce346bded508e2426798f825558be" />
    </MemoryRouter>
  </Provider>
)

describe('VaultTransactionsTable component', () => {
  it('renders correctly', () => {
    expect(toJson(wrapper)).toMatchSnapshot()
  })
})
