version: '3.2'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    networks:
      - default
    env_file:
      - 'env.influxdb'
    volumes:
      - ./influxdb-data:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "8125:8125/udp"
    networks:
      - default
    links:
      - influxdb
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    networks:
      - default
    links:
      - influxdb
    command: ['chronograf', '--influxdb-url=http://influxdb:8086']

  redis:
    image: redis:latest
    container_name: redis
    expose:
     - "6379"
    networks:
      - default

  arena:
    image: vshjxyz/arena:latest
    container_name: arena-stats
    ports:
      - "4567:4567"
    volumes:
      - ./config/arena/arena.conf.json:/opt/arena/src/server/config/index.json:ro
    networks:
      - default
    links:
      - redis

networks:
    default:
      driver: bridge
