version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      - ~/data/influxdb:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "8125:8125/udp"
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    environment:
      AUTH_DURATION: ${AUTH_DURATION}
      TOKEN_SECRET: ${TOKEN_SECRET}
      GH_CLIENT_ID: ${GH_CLIENT_ID}
      GH_CLIENT_SECRET: ${GH_CLIENT_SECRET}
      GH_ORGS: ${GH_ORGS}
    ports:
      - "8888:8888"
    links:
      - influxdb
    volumes:
      - ~/data/chronograf:/var/lib/chronograf
    command: ['chronograf', '--influxdb-url=http://influxdb:8086']

  redis:
    image: redis:5.0-rc-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis:/data
    command:
      ['redis-server', '--loglevel', 'notice', '--requirepass', '${REDIS_PASSWORD}']
    restart: always

  arena:
    image: vshjxyz/arena:latest
    container_name: arena
    ports:
      - "4567:4567"
    links:
      - redis
    volumes:
      - ./arena.prod.conf.json:/opt/arena/src/server/config/index.json:ro

  bull:
    container_name: bull
    environment:
      REDIS_HOST: dev-04.endpoint.network
      TELEGRAF_HOST: dev-04.endpoint.network
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    build:
      context: ../../
      dockerfile: ./packages/stats/Dockerfile
      args:
        - NPM_KEY=${NPM_KEY}
